apiVersion: v2
name: my-helm-chart
description: A Helm chart for my Kubernetes course project
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: rabbitmq
    version: 15.4.0
    repository: https://charts.bitnami.com/bitnami
