apiVersion: v1  #Версія апі до якого іде звернення
kind: Service #Тип апі до якого іде звернення
metadata:
  name: hw8-service  #Назва сервісу
spec:
  selector:
    app: hw8-app #Селектор лейблів подів яких стосується цей сервіс
  ports:
    - protocol: TCP #Протокол звязку
      port: 80  #Порт який слухає мервіс
      targetPort: 80  #Порт куди передається запит в под
  type: ClusterIP  #Тип підключення поду до сервісу