apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-sender-app
  template:
    metadata:
      labels:
        app: php-sender-app
    spec:
      containers:
        - name: nginx
          image: {{ .Values.php.nginx_image.repository }}:{{ .Values.php.nginx_image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: php-sender-container
          image: {{ .Values.php.php_image.repository }}:{{ .Values.php.php_image.tag }}
          volumeMounts:
            - name: nginx-config
              mountPath: /opt/bitnami/php/etc/php-fpm.d/www.conf
              subPath: www.conf
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "curl -o /app/index.php https://raw.githubusercontent.com/burundtriogeeks/DKHW/refs/heads/main/cp/php-sender/index.php"]
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
