apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-work
  namespace: my-cp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-work-app
  template:
    metadata:
      labels:
        app: php-work-app
    spec:
      containers:
        - name: php-work-container
          image: bitnami/php-fpm
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          lifecycle:
            postStart:
              exec:
                command: [ "curl", "-o", "/app/script.php", "https://raw.githubusercontent.com/burundtriogeeks/DKHW/refs/heads/main/cp/php-work/script.php"]
